### ISSUE TITLE
No lookforthechange package available

### ISSUE THREAD

**Issue by profundus59** [soCzech/MultiTaskObjectStates#3]
Hi, thank you for sharing your great work!

I am trying to reproduce the results but facing one problem.
The `train.py` file is importing the `lookforthechange` package but I do not see it in the repository.
Also it does not get installed using `pip` either.

I'm wondering if I could get the files for the `lookforthechange` folder which seems like it should be included in the repository. 

Thanks, I'll be looking forward for your feedback!

**Comment by soCzech** [comment]
The package is in the repository ;)
https://github.com/soCzech/MultiTaskObjectStates/tree/main/cuda_ops

**Comment by profundus59** [comment]
Thank you for your fast reply!
Sorry but I'm a bit new to CUDA code, could you please give me a short guide how to import the lookforthechange package? 

Would be great help. Thank you so much.

**Comment by soCzech** [comment]
`python setup.py install` ;)

**Comment by profundus59** [comment]
oh got it, thanks!
